import { IExperienceCompaniesData } from "./ExperienceCompanies.interface";

export const experienceCompaniesData: IExperienceCompaniesData[] = [
  {
    id: '0',
    company: 'SulAmérica',
    location: 'São Paulo, SP',
    position: 'Desenvolvedor Full Stack',
    timeLine: 'Ago 2022 - Presente',
    skills: [
      'Node', 
      'React', 
      'TypeScript',
      'Java', 
      'JavaScript',
      'Express.JS',
      'Jest', 
      'Redux', 
      'Contex API',
      'Git', 
      'Jira', 
      'Styled Components', 
      'Bitbucket',
      'Jekins',
      'Postman',
      'Firebase',
      'Google GPC',
      'Docker', 
      'Kubernets',
      'Scrum',
      'Linux'
    ],
    ordinalNumber: 'third',
  },
  {
    id: '1',
    company: 'Montenegro Labs',
    location: 'Natal, RN',
    position: 'Desenvolvedor Full Stack',
    timeLine: 'Fev 2022 - Ago 2022',
    skills: [
      'Node', 
      'React', 
      'TypeScript', 
      'JavaScript',
      'Next.JS',
      'Nest.JS',
      'Adonis.JS',
      'HTML5', 
      'CSS3',
      'Styled Components',
      'Git',
      'GitHub',
      'Docker',
      'PostegreSQL',
      'MySQL',
      'Scrum',
      'Linux'
    ],
    ordinalNumber: 'second',
  },
  {
    id: '2',
    company: 'Labaoratório de Inovação Tecnológica em Saúde',
    location: 'Natal, RN',
    position: 'Desenvolvedor Full Stack',
    timeLine: 'Dez 2019 - Fev 2022',
    skills: [
      'JavaScript',
      'PHP',
      'Laravel',
      'HTML5', 
      'CSS3',
      'Sass',
      'Git',
      'GirLab',
      'Docker',
      'PostegreSQL',
      'MySQL',
      'Scrum',
      'Linux',
    ],
    ordinalNumber: 'first',
  }
];